### ISSUE TITLE
Consider setting `.spec.ttlSecondsAfterFinished` in the Job

### ISSUE THREAD

**Issue by cskinfill** [k3s-io/helm-controller#245]
Setting `.spec.ttlSecondsAfterFinished` to some value will automatically clean up and remove the Job and associated Pods (see [here](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) for more details).  This way, the Jod-related Pod doesn't linger on in a `Completed` state when someone lists the pods in a namespace.

I think the change would go somewhere in this method https://github.com/k3s-io/helm-controller/blob/master/pkg/controllers/chart/chart.go#L375.  This might be something added to the `kind: HelmChart` resource or a global configuration set on the controller or both.

**Comment by brandond** [comment]
The HelmChart controller does not actually watch the Job to see if it completes. It just periodically re-applies the desired Job spec, assuming that no change means everything is correct. If the Job was cleaned up after it completed, the Helm controller would just re-create it, and it would run again.

In order to allow the Jobs to be cleaned up after they complete, we would need to actually watch the Jobs, ensure that they eventually run to completion, and then store that information somewhere in the HelmChart resource - similar to how the Job controller watches Pods to ensure that they run successfully. This would be a fair bit of additional complexity, and is not currently planned.

**Comment by cskinfill** [comment]
Ok.  Closing this issue.
