### ISSUE TITLE
spec.failurePolicy: reinstall as a default is extremely dangerous

### ISSUE THREAD

**Issue by riuvshyn** [k3s-io/helm-controller#246]
Having `spec.failurePolicy` defaulted to `reinstall` could cause serious incident. 
Example: using `HelmChart` to install CNI such as Cilium, with next version upgrade chart is failing or being blocked with some admission controller such as kyverno. Then helm-controller removes Cilium and tries to install it again which might also fail if that was blocked by admission controller.

**Comment by brandond** [comment]
K3s and RKE2 depend on the Helm controller being able to uninstall and reinstall packaged charts in order to ensure that the components are updated. We added control over failure policy as a way for administrators to opt in to manually handling stuck charts, but we do not plan to change the default.
